language: ruby
dist: wily
rvm:
  - 2.3.0

branches:
    only:
      - master

# Install PhantomJS 2.0 from source binary, remove once TravisCI environment has PhantomJS 2.0 installed
# see https://github.com/travis-ci/travis-ci/issues/3225 for more details
before_install:
  - ./bin/get-phantomjs

before_script:
  - sudo apt-get install pdftk

script:
  - bundle exec rake

bundler_args: "--without development staging production"
cache:
  directories:
    - vendor/bundle
    - travis-phantomjs

notifications:
  email: false
